import React from 'react';
import { Check, Coins, ListChecks, Sparkles, X } from 'lucide-react';
import { Quest } from '../../types';
import { useGameState } from '../../context/GameStateContext';

export const QuestModal: React.FC<{ quest?: Quest; onClose: () => void }> = ({ quest, onClose }) => {
  const { completeQuest, toggleSubtask } = useGameState();
  if (!quest) return null;
  return <div className="modal-backdrop"><div className="modal-panel max-w-lg"><div className="flex items-start justify-between"><div><span className="tag bg-cyan-400/10 text-cyan-300">{quest.type.toUpperCase()}</span><h2 className="mt-3 text-2xl font-black text-white">{quest.title}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={20} /></button></div><p className="mt-4 leading-7 text-slate-400">{quest.description || 'No description added.'}</p>{quest.subtasks && quest.subtasks.length > 0 && <div className="mt-6 border-t border-white/10 pt-5"><div className="mb-3 flex items-center gap-2"><ListChecks size={16} className="text-cyan-300" /><h3 className="text-sm font-bold uppercase tracking-wider text-slate-300">Mission checklist</h3></div><div className="space-y-2">{quest.subtasks.map((task) => <label key={task.id} className="flex cursor-pointer items-center gap-3 rounded-lg border border-white/10 bg-white/[.03] p-3 text-sm text-slate-300"><input type="checkbox" checked={task.completed} onChange={() => toggleSubtask(quest.id, task.id)} className="accent-cyan-400" /><span className={task.completed ? 'text-slate-600 line-through' : ''}>{task.title}</span></label>)}</div></div>}<div className="mt-6 grid grid-cols-3 gap-3"><div className="stat-card"><Sparkles size={16} className="text-purple-300" /><strong className="mt-2 block text-lg text-white">+{quest.reward.xp ?? 0}</strong><span>experience</span></div><div className="stat-card"><Coins size={16} className="text-amber-300" /><strong className="mt-2 block text-lg text-white">+{quest.reward.credits ?? 0}</strong><span>credits</span></div><div className="stat-card"><Check size={16} className="text-emerald-300" /><strong className="mt-2 block text-lg text-white">{quest.completed ? 'Done' : 'Open'}</strong><span>status</span></div></div><div className="mt-6 flex justify-end gap-3"><button className="button-secondary" onClick={onClose}>Close</button><button disabled={quest.completed} className="button-primary" onClick={() => { completeQuest(quest.id); onClose(); }}>{quest.completed ? 'Completed' : 'Complete quest'}</button></div></div></div>;
};

export default QuestModal;
